name: 'BunnyCDN Deploy'
description: 'WIP action for deploying to BunnyCDN via the official BunnyCDN .Net SDK'
branding:
  icon: upload-cloud
  color: orange
inputs:
  workspace:
    description: 'The workspace directory.'
    default: '/github/workspace'
  directory:
    description: 'The root directory to upload from (relative to workspace). Example, "path/to/build/artifacts".'
    required: true
  branch-current-name:
    description: 'The name of the current GitHub Branch. Example, "main".'
    required: true
  branch-main-name:
    description: 'The name of the main GitHub Branch. Example, "main".'
    default: 'main'
  api-key:
    description: 'The API key for the BunnyCDN account which owns the target DNS Zone'
    required: true
  dns-zone-id:
    description: 'The Id of the target DNS Zone.'
    required: true
  dns-subdomain:
    description: 'The subdomain for deployment in the target DNS Zone. If left blank, deploys to the root domain.'
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '-w'
  - ${{ inputs.workspace }}
  - '-d'
  - ${{ inputs.directory }}
  - '-c'
  - ${{ inputs.branch-current-name }}
  - '-m'
  - ${{ inputs.branch-main-name }}
  - '-a'
  - ${{ inputs.api-key }}
  - '-i'
  - ${{ inputs.dns-zone-id }}
  - '-s'
  - ${{ inputs.dns-subdomain }}