name: 'BunnyCDN Deploy'
description: 'WIP action for deploying to BunnyCDN via the official BunnyCDN .Net SDK'
branding:
  icon: upload-cloud
  color: orange
inputs:
  workspace:
    description: 'The workspace directory.'
    required: false
    default: '/github/workspace'
  directory:
    description: 'The root directory to upload from (relative to workspace). Example, "path/to/build/artifacts".'
    required: true
  api-key:
    description: 'The API key for the BunnyCDN account which owns the target Storage/Pull Zones'
    required: true
  dns-zone-id:
    description: 'The Id of the target DNS Zone.'
    required: true
  dns-root-subdomain:
    description: 'The root subdomain for deployment in the target DNS Zone.'
    required: true
  branch:
    description: 'The name of the GitHub Branch. Example, "main".'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '-w'
  - ${{ inputs.workspace }}
  - '-d'
  - ${{ inputs.directory }}
  - '-a'
  - ${{ inputs.api-key }}
  - '-z'
  - ${{ inputs.dns-zone-id }}
  - '-s'
  - ${{ inputs.dns-root-subdomain }}
  - '-b'
  - ${{ inputs.branch }}